collections:
  authors:
    output: true

defaults:
  - scope: 
      path: ""
    values: 
      layout: "page"
  - scope:
      path: ""
      type: "authors"
    values: 
      layout: "author"    
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      by: "xx"
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

title: My awesome blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 This is the description of the my awesome blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll  

theme: minima
# remote_theme: jekyll/minima

header_pages:
  - about.md
  - staff.html

date_format: "%b %-d, %Y"



# paginate: 3
# paginate_path: "/blog/page:num/"