collections:
  authors:
    output: true

defaults:
  - scope: 
      path: ""
    values: 
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values: 
      layout: "author"    
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      by: "xx"
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag